repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff format
        entry: uv run --locked ruff format --check
        language: system
        types: [python]
      - id: ruff-check
        name: Ruff lint
        entry: uv run --locked ruff check
        language: system
        types: [python]
      - id: mypy
        name: Mypy
        entry: uv run --locked mypy src/stocknews
        language: system
        pass_filenames: false
        types: [python]
      - id: pyright
        name: Pyright
        entry: uv run --locked pyright
        language: system
        pass_filenames: false
        types: [python]
